@startuml

title __SERVICE's Class Diagram__\n

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.IChatMessageService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + findById()
            {abstract} + getAll()
            {abstract} + getLastMessages()
            {abstract} + openChat()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.IChatService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + findById()
            {abstract} + findByUsers()
            {abstract} + getAll()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.ICommentService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + findById()
            {abstract} + getAll()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.IFollowService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + getAll()
            {abstract} + getFollowByUsers()
            {abstract} + getFollowers()
            {abstract} + getFollowing()
            {abstract} + getSuggestions()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.ILikeService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + findById()
            {abstract} + getAll()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.INotificationService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + findById()
            {abstract} + findNewNotifications()
            {abstract} + findPersonalNotifications()
            {abstract} + getAll()
            {abstract} + updateNotifications()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.IPostService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + findById()
            {abstract} + getAll()
            {abstract} + getNewsFeedPosts()
            {abstract} + getPersonalPosts()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.IProfileService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + findById()
            {abstract} + getAll()
            {abstract} + search()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.IRoleService {
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.ISecurityService {
            {abstract} + isAuthenticated()
            {abstract} + login()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.IStoryService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + findById()
            {abstract} + getAll()
        }
      }
    }
  }
  

  namespace  {
    namespace om.licenta.socialmedia {
      namespace service {
        interface com.licenta.socialmedia.service.IUserService {
            {abstract} + add()
            {abstract} + delete()
            {abstract} + findById()
            {abstract} + findByUsername()
            {abstract} + getAll()
            {abstract} + updateWithoutPassword()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
